name: GCS Deployment

# Controls when theq action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your arepository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # 拉取最新的兩次提交

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.CGP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Git
      run: |
        git config --global user.name 'hairychang'
        git config --global user.email 'alexchang19931219@gmail.com'

    - name: Deploy via GCS
      run: |
        # 獲取上次成功的提交和當前提交的差異
        if [ -z "$(git rev-parse HEAD~1)" ]; then
          echo "No previous commit found, only listing current commit changes."
          CHANGED_FILES=$(git diff --name-only HEAD)
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
        fi
        echo "Changed files: $CHANGED_FILES"
        CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | sed 's|/[^/]*$||' | sort | uniq)
        gsutil -m cp -r ./Files/Tp/* gs://github-action-gcs/Files/
        rm -rf ./Files/Tp/
        git rm -r ./Files/Tp
    
    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
      run: |
        git commit -m "Remove folder via GitHub Actions"
        git push
      
#change
        
# gsutil -m rm -rf gs://github-action-gcs/Files/ || echo "$?"
# gsutil -m rm -rf gs://github-action-gcs/* || echo "$?"
# name: Upload to Google Cloud Storage change account
# gsutil -m cp -r ./$CHANGED_FILES gs://github-action-gcs/$CHANGED_FOLDERS