name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - main  # 在推送到main分支時觸發

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_FILE }}

      - name: Authenticate to Google Cloud
        run: echo "${{ secrets.GCP_KEY_FILE }}" > /tmp/key.json

      - name: Activate Service Account
        run: gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Deploy via GCS
      run: |
        gsutil -m rm -rf gs://github-action-gcs/* || echo "$?"
        gsutil -m cp -r * gs://github-action-gcs/

# name: Upload to Google Cloud Storage

# on:
#   push:
#     branches:
#       - main  # 在推送到main分支時觸發

# jobs:
#   upload-to-gcs:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0
#         with:
#           version: 'latest'
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_KEY_FILE }}

#       - name: Authenticate to Google Cloud
#         run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_FILE }}

#       - name: Upload to GCS
#         run: |
#           gsutil -m rm -rf gs://github-action-gcs/* || echo "$?"
#           gsutil -m cp -r * gs://github-action-gcs/