name: GCS Deployment

# Controls when theq action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: 
    - fac2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your arepository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.CGP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy via GCS
      run: |
        gsutil -m cp -r ./tp/* gs://github-action-gcs/fac1

# gsutil -m rm -rf gs://github-action-gcs/* || echo "$?"
# name: Upload to Google Cloud Storage change account

# on:
#   push:
#     branches:
#       - main  # 在推送到main分支時觸發

# jobs:
#   upload-to-gcs:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0
#         with:
#           version: 'latest'
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_KEY_FILE }}

#       - name: Authenticate to Google Cloud
#         run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_FILE }}

#       - name: Upload to GCS
#         run: |
#           gsutil -m rm -rf gs://github-action-gcs/* || echo "$?"
#           gsutil -m cp -r * gs://github-action-gcs/